target "GTUIKitAdditionsDemo" do
  pod "GTUIKitAdditions", :path => "../GTUIKitAdditions.podspec"
end

target "GTUIKitAdditionsDemoTests" do
  pod "GTUIKitAdditions", :path => "../GTUIKitAdditions.podspec"
end
